language: rust

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh -O
  - ./after_success.sh

env:
  global:
    secure: FiuMAJ7ddQ7qbGramIH0ef9kMbKwSfwmUOXaIhoJuB5b6T5eHjyWiSvLPxFth/4XWFGzVFTT7phkBlK0zVOSF18G2ivGluHZ7+YSUWpgrW+4mY35pG4kpyKUz2baazKvFNRpoHi8VqwWSwYAKTGvlOLw+mmDdf5WDBSRyQByOC4=
