[package]
name = "tar"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/tar"
homepage = "https://github.com/stainless-steel/tar"
documentation = "https://stainless-steel.github.io/tar"
description = "The library provides basic operations with tar archives."

[dependencies]
libtar-sys = "0.0.1"
